### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by samarthsikotara** [mverschu/mailspoofsent#1]
This is not working

**Comment by mverschu** [comment]
The tool is working just fine if all parameters are supplied correctly. Here is an example on how to use it. Use the --mail-envelope in combination with a mail domain under your control and the --mail-from with an address you want to spoof. Ofcourse this is only possible when DMARC is not configured or configured using the policy none.

See: https://www.youtube.com/watch?v=M5bgfsaBBuc

**Comment by mverschu** [comment]
As the README.md states personal mail only works half of the time because of extra implemented security,

**Comment by samarthsikotara** [comment]
Thank you, yes i checked that. is there a way to send bulk emails to 100K+ emails daily including gmail addresses?

**Comment by mverschu** [comment]
I cannot help you doing anything unethical, the tool was designed for security professionals to proof the fact that mail spoofing is possible.

Please stop creating issues as this is not an actual issue for the tool.

Thanks.
