### ISSUE TITLE
From: hola@mail.XXXXX.com: No such file or directory

### ISSUE THREAD

**Issue by mourad92** [mverschu/mailspoofsent#2]
Postfix and/or mailutils are not installed. Do you want to install them now? (y/n) n
[+] Updating hostname to yandex.com so PTR record lookup is for domain under control...
[+] Updating Postfix configuration...
[+] Adding List-Unsubscribe header...
[+] Replacing example.com domain with domain from mail_from argument...
[-] Postfix is already started, ready to start...
[+] Setting smtp.mailfrom address to mail_envelope value to bypass SPF...
[+] Applying changes to postfix configuration...
Redirecting to /bin/systemctl restart postfix.service
[-] Cleaning up for the next run...
[+] Sending email...
From: hola@mail.XXXXXX.com: No such file or directory
[-] Failed to send email!

**Comment by mverschu** [comment]
Seems the tool tells the utilities that are required are not installed. Can you install them and try again?
